CREATE TABLE PESSOA(ID INT PRIMARY KEY AUTO_INCREMENT, NOME VARCHAR(50) NOT NULL, DATA_NASCIMENTO DATE NOT NULL,  ATIVO BOOLEAN NOT NULL) ;

CREATE SEQUENCE pessoa_seq
  INCREMENT 1
  MINVALUE 1
  MAXVALUE 999999999999999
  START 1
  CACHE 1;



